import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      email: "fluid@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Le Classique",
      slug: "Le-Classique",
      category: "Shirts",
      image: "/images/Recto-min.png",
      isFeatured: true,
      featuredImage: "/images/Recto-min.png",
      price: 39.99,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Le Classique",
      slug: "Le-Classique1",
      category: "Shirts",
      image: "/images/Verso-min.png",
      isFeatured: true,
      featuredImage: "/images/Verso-min.png",
      price: 39.99,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "L’intrépide",
      slug: "L-intrépide",
      category: "Shirts",
      image: "/images/sweat2-Recto-min.png",
      price: 39.99,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "L’intrépide",
      slug: "L-intrépide1",
      category: "Pants",
      image: "/images/sweat2-Verso-min.png",
      price: 39.99,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
  ],
};
export default data;
